### ISSUE TITLE
Background is above logo and text

### ISSUE THREAD

**Issue by alexjsteffen** [djdynam/Axia#1]
**Platform**: macOS

I have encountered an issue with the formatting of the background of the template. The issue relates to the fact that the background is above the rest of the text. I have included a screenshot and a small video with that discussion. Let me know if you have any questions.

![Screen Shot 2020-11-09 at 9 08 46 PM](https://user-images.githubusercontent.com/52205871/98618756-d3af7c80-22cf-11eb-9f7e-b9f5ad23d859.png)

[Video Description](https://dr.ajhs.io/f/1a73adc92af84e2c8551/)

**Comment by djdynam** [comment]
I have fixed this bug in JavaScript.
