### ISSUE TITLE
Fix Incorrect location of search bar and AXIA logo in search results

### ISSUE THREAD

**Issue by alexjsteffen** [djdynam/Axia#3]
Issue: AXIA logo is too large and the search bar is still on top. 

**See Below**

![Screenshot from 2020-11-10 12-15-00](https://user-images.githubusercontent.com/52205871/98709662-ae168780-2350-11eb-8b6e-9db5d621d9d1.png)

**Comment by djdynam** [comment]
I've minified the css, and it should fix the problem
